name: Check
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check
        run: "deno task check"
